### Site metadata ###

title: Trends

description: >-
  Graphs of trends around web searches, social media and economic indicators
github_username: MichaelCurrin

### Build settings ###

baseurl: "/trends"
url: ""

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - "showcase.md"
  - "blog.md"

exclude:
  - vendor/
  - LICENSE
  - Makefile
  - README.md
  - Gemfile
